### PR TITLE
Bump to ver. 3.6.0

### PR DESCRIPTION
**Pull request by igortg**

### CODE REVIEW

**Comment by CJ-Wright** [comment]
Should this have run on windows?

**Comment by igortg** [comment]
Yup, should I rerender?

**Comment by CJ-Wright** [comment]
@conda-forge-admin, please rerender

**Comment by CJ-Wright** [comment]
Hmm the rerender still didn't catch appveyor's eye, idk what is going on here.

**Comment by jakirkham** [comment]
Have triggered an AppVeyor build.

As to what happened, sometimes AppVeyor gets rate limited. Please read this [comment]( https://github.com/appveyor/ci/issues/1002#issuecomment-253617092 ) and what follows for more details. Morale of the story is one of our bots is used to count GitHub API usage against instead of individual users like what other CIs presumably do.

**Comment by CJ-Wright** [comment]
Ah, thank you! That's rough though.

**Comment by igortg** [comment]
I'm sorry, there were already 2 PRs bumping pymongo version to 3.6... I'm removing this one

**Pull request closed without merging**
