### PR TITLE
Build aarch + ppc64le

### PR DESCRIPTION
**Pull request by hmaarrfk**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@conda-forge-admin, please rerender

**Comment by hmaarrfk** [comment]
Needs https://github.com/conda-forge/mongo-tools-feedstock/pull/10 i think

**Comment by CJ-Wright** [comment]
Was the bot PR opened in error?

**Comment by hmaarrfk** [comment]
I guess so

**Comment by nehaljwani** [comment]
@hmaarrfk Could you please try rebasing? The missing deps for aarch64 are available now.

**Comment by hmaarrfk** [comment]
Thanks for the ping.

Seems like there has been some reorg. 

I'm goign to go with https://github.com/conda-forge/pymongo-feedstock/pull/33

**Pull request closed without merging**
