### PR TITLE
Enable aarch64

### PR DESCRIPTION
**Pull request by hmaarrfk**
@conda-forge-admin, please rerender

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
Seems like pypy is failing on travis. it also seemed to have failed before this PR.

**Comment by nehaljwani** [comment]
Could put a skip for pypy + ppc64le and deal with it when someone actually asks for it :stuck_out_tongue_winking_eye:

**Comment by hmaarrfk** [comment]
That would break all of the downstream migration though.

@conda-forge-admin please rerender

**Comment by tacaswell** [comment]
From a quick skim of the failures it looks plausible that the failures are either due to the tests not being due to pypy not quite being a drop-in replacement for CPython (and that they are in a test file called `legacy`) I think skipping the tests is pragmatic.

It may be useful for someone to track down if these are pypy or pymongo bugs, but merging as-is.

**Comment by hmaarrfk** [comment]
Thanks @tacaswell I came to the same conclusion.

With numpy, I typically use pytest's skipping functionality to make skipping more precise.

**Pull request merged**
