### PR TITLE
Use pypi as source

### PR DESCRIPTION
**Pull request by blink1073**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by blink1073** [comment]
@conda-forge-admin, please rerender

**Review by ShaneHarvey — APPROVED** [review]

**Comment by blink1073** [comment]
Error seems unrelated.  There are no changes to the linux builds, but the failure is:

```
Setting up cross-python
ERROR: 'HOST_GNU_TYPE'
```

**Comment by blink1073** [comment]
@hmaarrfk, any idea why aarch64 would start failing on Linux Python 3.8 and 3.9 with `ERROR: 'HOST_GNU_TYPE'`?

**Comment by hmaarrfk** [comment]
I don't know. I would try to build with emulated for now.

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by hmaarrfk** [comment]
see changes i made. feel free to revert.

**Comment by hmaarrfk** [comment]
(it is hard to suggest on files that don't show up)

**Comment by blink1073** [comment]
Thank you!

**Pull request merged**
