### PR TITLE
[3.x.x] rebuild 3.13.0 with python 3.12 and 3.13

### LINKED ISSUE #95: Possibility of building packages for pymongo 3 for newer versions of python
### Comment:

Would it be possible to build pymongo 3 for newer version of pythons? (e.g., 3.12, 3.13)

Assuming, of course, that they work out of the box. Sadly there are many packages that still depend on pymongo 3, which cascades down and limit other packages to python 3.11 due to that.

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

fixes #95

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@conda-forge/pymongo anyone have any concerns about this?  Test are passing for python 3.12 and 3.13, for what it's worth...

**Comment by xylar** [comment]
I can add the same constraint on setuptools to host but it won't be included at runtime regardless. The constraint on test is just because of an argument, tests_require, that has been dropped.

**Comment by xylar** [comment]
@tacaswell, are you suggesting that setuptools be added as a runtime requirement? I don't see any evidence that this is needed.

**Comment by blink1073** [comment]
I can confirm setuptools is only used to build C extensions, it is not used at runtime.

**Comment by tacaswell** [comment]
I was asking to confirm that setuptools was used in invoking the tests not that it was used someplace in the run time that the tests exercised.

**Comment by xylar** [comment]
Great, glad we got that worked out.

**Pull request merged**
