### PR TITLE
Update maintainers

### PR DESCRIPTION
**Pull request by blink1073**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by blink1073** [comment]
@ShaneHarvey please confirm you'd like to be added as a maintainer

**Comment by blink1073** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
To add maintainers please use https://conda-forge.org/docs/maintainer/infrastructure.html#conda-forge-admin-please-add-user-username

**Comment by blink1073** [comment]
> To add maintainers please use conda-forge.org/docs/maintainer/infrastructure.html#conda-forge-admin-please-add-user-username

TIL, thanks!

**Pull request closed without merging**
